# Generated by Django 3.1.7 on 2021-03-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='db',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Mname', models.CharField(max_length=20)),
                ('Mphno', models.CharField(max_length=10)),
                ('Mpassword', models.CharField(max_length=12)),
                ('Memail', models.EmailField(max_length=30)),
            ],
        ),
    ]
