# Generated by Django 3.1.7 on 2021-04-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='db',
            name='Mprof',
            field=models.CharField(default='student', max_length=12),
        ),
    ]
